# Generated by Django 3.1.7 on 2021-03-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('poll', '0002_poll2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll2',
            name='question',
        ),
    ]
