# Generated by Django 3.1.7 on 2021-03-17 22:16

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('poll', '0003_remove_poll2_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option_one',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_one_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_three',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_three_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_two',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_two_count',
        ),
    ]
