# Generated by Django 3.1.7 on 2021-03-17 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('poll', '0004_auto_20210317_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll2',
            name='poll_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
    ]
