# Generated by Django 3.1.7 on 2021-03-18 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('poll', '0006_remove_poll2_poll_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='question_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll2',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
    ]
